export const ImageUrls = [
  "3BHK-All-photos/BEDROOM 1 (MASTER) 1.jpg",
  "3BHK-All-photos/BEDROOM 1 (MASTER) 2.jpg",
  "3BHK-All-photos/BEDROOM 1 (MASTER) 3.jpg",
  "3BHK-All-photos/BEDROOM 1 (MASTER) 4.jpg",
  "3BHK-All-photos/BEDROOM 2_1.jpg",
  "3BHK-All-photos/BEDROOM 2_2.jpg",
  "3BHK-All-photos/BEDROOM 2_3.jpg",
  "3BHK-All-photos/BEDROOM 2_4.jpg",
  "3BHK-All-photos/BEDROOM 3_1.jpg",
  "3BHK-All-photos/BEDROOM 3_2.jpg",
  "3BHK-All-photos/BEDROOM 3_3.jpg",
  "3BHK-All-photos/KITCHEN 1.jpg",
  "3BHK-All-photos/KITCHEN 2.jpg",
  "3BHK-All-photos/LIVVING _ DINING ROOM 1.jpg",
  "3BHK-All-photos/LIVVING _ DINING ROOM 2.jpg",
  "3BHK-All-photos/LIVVING _ DINING ROOM 3.jpg",
  "3BHK-All-photos/LIVVING _ DINING ROOM 4.jpg",
  "3BHK-All-photos/LIVVING _ DINING ROOM 5.jpg",
]